"""AWS CDK stack provisioning VPC, RDS PostgreSQL (serverless v2) and Secrets Manager secret."""
from aws_cdk import (
    Stack,
    CfnOutput,
    RemovalPolicy,
    Duration,
    aws_ec2 as ec2,
    aws_rds as rds,
    aws_secretsmanager as sm,
    aws_cloudwatch as cw,
    aws_cloudwatch_actions as cw_actions,
    aws_sns as sns,
    aws_sns_subscriptions as subs,
    aws_ecr as ecr,
    aws_iam as iam,
    aws_cognito as cognito,
)
import aws_cdk.aws_apprunner_alpha as apprunner
from constructs import Construct
import os


class GreatFitInfraStack(Stack):
    """Infrastructure stack for Great Fit production deployment."""

    def __init__(self, scope: Construct, construct_id: str, **kwargs):
        super().__init__(scope, construct_id, **kwargs)

        # VPC across 2 AZs with public + isolated subnets
        vpc = ec2.Vpc(
            self, "GreatFitVpc",
            max_azs=2,
            nat_gateways=1,                    # shared NAT
            subnet_configuration=[
                ec2.SubnetConfiguration(       # 10.0.0.0/24 & 10.0.1.0/24
                    name="public",
                    subnet_type=ec2.SubnetType.PUBLIC,
                    cidr_mask=24,
                ),
                ec2.SubnetConfiguration(       # 10.0.2.0/24 & 10.0.3.0/24
                    name="isolated",
                    subnet_type=ec2.SubnetType.PRIVATE_ISOLATED,
                    cidr_mask=24,
                ),
                ec2.SubnetConfiguration(       # 10.0.4.0/24 & 10.0.5.0/24
                    name="private-egress",
                    subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS,
                    cidr_mask=24,
                ),
            ],
        )

        # Secrets Manager – autogenerated master credentials
        db_secret = sm.Secret(
            self,
            "DbSecret",
            generate_secret_string=sm.SecretStringGenerator(
                exclude_punctuation=True,
                include_space=False,
                generate_string_key="password",
                secret_string_template='{"username":"gfadmin"}',
            ),
        )

        # ---------------- Cognito User Pool ---------------- #
        user_pool = cognito.UserPool(
            self,
            "GfUsers",
            self_sign_up_enabled=True,
            sign_in_aliases=cognito.SignInAliases(email=True),
            standard_attributes=cognito.StandardAttributes(
                email=cognito.StandardAttribute(required=True, mutable=True)
            ),
            removal_policy=RemovalPolicy.DESTROY,
        )

        # App client for SPA / Hosted UI implicit flow
        app_client = user_pool.add_client(
            "WebClient",
            auth_flows=cognito.AuthFlow(user_srp=True, user_password=True),
            o_auth=cognito.OAuthSettings(
                flows=cognito.OAuthFlows(implicit_code_grant=True),
                scopes=[cognito.OAuthScope.OPENID, cognito.OAuthScope.EMAIL],
                callback_urls=["https://greatfit.app/"],
                logout_urls=["https://greatfit.app/"],
            ),
        )

        # Hosted UI domain (https://greatfit.auth.<region>.amazoncognito.com)
        domain = user_pool.add_domain(
            "GfDomain",
            cognito_domain=cognito.CognitoDomainOptions(domain_prefix="greatfit"),
        )

        # RDS Aurora PostgreSQL Serverless v2 cluster
        cluster = rds.DatabaseCluster(
            self,
            "PostgresCluster",
            engine=rds.DatabaseClusterEngine.aurora_postgres(
                version=rds.AuroraPostgresEngineVersion.VER_15_5,
            ),
            writer=rds.ClusterInstance.serverless_v2("writer"),
            serverless_v2_min_capacity=0.5,   # ACUs
            serverless_v2_max_capacity=2,     # ACUs
            vpc=vpc,
            credentials=rds.Credentials.from_secret(db_secret),
            default_database_name="greatfit",
            subnet_group=rds.SubnetGroup(
                self,
                "DbSubnetGroup",
                description="Isolated subnets for RDS",
                vpc=vpc,
                subnet_group_name="gf-db-subnets",
                vpc_subnets=ec2.SubnetSelection(
                    subnet_type=ec2.SubnetType.PRIVATE_ISOLATED
                ),
            ),
            removal_policy=RemovalPolicy.DESTROY,
        )

        # --- Container Repository --- #
        ecr_repo = ecr.Repository.from_repository_name(
            self, "AppRepository", repository_name="great-fit"
        )

        # --- App Runner Service --- #

        # Secret holding external API key (must exist beforehand)
        openrouter_secret_name = os.getenv("OPENROUTER_SECRET_NAME", "OPENROUTER_API_KEY")
        openrouter_secret = sm.Secret.from_secret_name_v2(
            self, "OpenRouterSecret", openrouter_secret_name
        )

        # Instance role to allow reading secrets
        instance_role = iam.Role(
            self,
            "AppRunnerInstanceRole",
            assumed_by=iam.ServicePrincipal("tasks.apprunner.amazonaws.com"),
        )
        db_secret.grant_read(instance_role)
        openrouter_secret.grant_read(instance_role)

        # Allow basic Cognito read actions (ListUsers for email lookup etc.)
        instance_role.add_to_policy(
            iam.PolicyStatement(
                effect=iam.Effect.ALLOW,
                actions=[
                    "cognito-idp:ListUsers",
                    "cognito-idp:GetUser",
                ],
                resources=[user_pool.user_pool_arn],
            )
        )

        # DATABASE_URL using dynamic reference to password secret
        db_password = db_secret.secret_value_from_json("password").to_string()
        database_url = (
            f"postgresql://gfadmin:{db_password}@{cluster.cluster_endpoint.hostname}:5432/greatfit"
        )

        # --- Networking: allow App Runner to reach RDS via VPC Connector --- #
        # Security group for App Runner ENIs
        apprunner_sg = ec2.SecurityGroup(
            self,
            "AppRunnerSG",
            vpc=vpc,
            description="Security group for App Runner to access RDS",
            allow_all_outbound=True,
        )

        # Allow connections from App Runner to Postgres
        cluster.connections.allow_from(
            apprunner_sg,
            ec2.Port.tcp(5432),
            "App Runner access to Aurora Postgres"
        )

        vpc_connector = apprunner.VpcConnector(
            self,
            "AppVpcConnector",
            vpc=vpc,
            vpc_subnets=ec2.SubnetSelection(
                subnet_group_name="private-egress"
            ),
            security_groups=[apprunner_sg],
        )

        obs_cfg = apprunner.ObservabilityConfiguration(
            self, "Obs",
            observability_configuration_name="gf-default",
            trace_configuration_vendor=apprunner.TraceConfigurationVendor.AWSXRAY,
        )

        apprunner_service = apprunner.Service(
            self,
            "GreatFitAppRunner",
            source=apprunner.Source.from_ecr(
                repository=ecr_repo,
                tag_or_digest="latest",
                image_configuration=apprunner.ImageConfiguration(
                    port=8080,
                    environment_variables={
                        "DB_HOST": cluster.cluster_endpoint.hostname,
                        "DB_PORT": "5432",
                        "DB_NAME": "greatfit",
                        "DB_USER": "gfadmin",
                        "AWS_REGION": self.region,
                        "COGNITO_USER_POOL_ID": user_pool.user_pool_id,
                        "COGNITO_APP_CLIENT_ID": app_client.user_pool_client_id,
                    },
                    environment_secrets={
                        "DB_PASSWORD": apprunner.Secret.from_secrets_manager(
                            db_secret, field="password"
                        ),
                        "OPENROUTER_API_KEY": apprunner.Secret.from_secrets_manager(
                            openrouter_secret
                        ),
                    },
                ),
            ),
            cpu=apprunner.Cpu.ONE_VCPU,
            memory=apprunner.Memory.TWO_GB,
            instance_role=instance_role,
            vpc_connector=vpc_connector,
            observability_configuration=obs_cfg
        )

        # Outputs
        CfnOutput(self, "DbEndpoint", value=cluster.cluster_endpoint.hostname)
        CfnOutput(self, "DbSecretArn", value=db_secret.secret_arn)
        CfnOutput(self, "EcrRepoUri", value=ecr_repo.repository_uri)
        CfnOutput(self, "AppRunnerUrl", value=apprunner_service.service_url)

        # Cognito outputs
        CfnOutput(self, "UserPoolId", value=user_pool.user_pool_id)
        CfnOutput(self, "UserPoolClientId", value=app_client.user_pool_client_id)
        CfnOutput(
            self,
            "CognitoDomainUrl",
            value=f"https://{domain.domain_name}.auth.{self.region}.amazoncognito.com",
        )

        # --- Monitoring & Alarms --- #
        # SNS topic for alarm notifications (add your email via env var ALERT_EMAIL or manually)
        alert_email = os.getenv("ALERT_EMAIL")
        topic = sns.Topic(self, "AlarmTopic", display_name="GreatFitAlarms")
        if alert_email:
            topic.add_subscription(subs.EmailSubscription(alert_email))

        # CPU Utilization alarm (>80% for 5 mins)
        cpu_metric = cluster.metric_cpu_utilization().with_(period=Duration.minutes(1))

        cpu_alarm = cw.Alarm(
            self,
            "DbHighCpu",
            metric=cpu_metric,
            evaluation_periods=3,
            datapoints_to_alarm=3,
            threshold=80,
            comparison_operator=cw.ComparisonOperator.GREATER_THAN_THRESHOLD,
            alarm_description="RDS Aurora CPU > 80%",
            alarm_name="GreatFit-RDS-HighCPU",
            actions_enabled=True,
        )

        # Wire alarm to SNS topic
        cpu_alarm.add_alarm_action(cw_actions.SnsAction(topic))

        # CloudWatch Dashboard
        dashboard = cw.Dashboard(self, "GreatFitDashboard", dashboard_name="GreatFit")
        dashboard.add_widgets(
            cw.GraphWidget(
                title="RDS CPU Utilization",
                left=[cpu_metric],
            )
        )
